import { createMuiTheme } from "@material-ui/core/styles";

// This is the main theme of the website. Generated by https://in-your-saas.github.io/material-ui-theme-editor.

// Pass the object to ThemeProvider component and it will apply the theme to the subtree.
const BeerGameTheme = createMuiTheme({
  palette: {
    common: { black: "#000", white: "#fff" },
    background: { paper: "#fff", default: "#fafafa" },
    primary: {
      light: "rgba(239, 220, 213, 1)",
      main: "rgba(188, 170, 164, 1)",
      dark: "rgba(140, 123, 117, 1)",
      contrastText: "#fff",
    },
    secondary: {
      light: "rgba(178, 254, 247, 1)",
      main: "rgba(128, 203, 196, 1)",
      dark: "rgba(79, 154, 148, 1)",
      contrastText: "#fff",
    },
    error: {
      light: "#e57373",
      main: "#f44336",
      dark: "#d32f2f",
      contrastText: "#fff",
    },
    text: {
      primary: "rgba(0, 0, 0, 0.87)",
      secondary: "rgba(0, 0, 0, 0.54)",
      disabled: "rgba(0, 0, 0, 0.38)",
      hint: "rgba(0, 0, 0, 0.38)",
    },
  },
});

export default BeerGameTheme;
